### ISSUE TITLE
Which folder?

### ISSUE THREAD

**Issue by Scrut1ny** [codsec/EFT-texture-esp#1]
Do you legit mean move the "EFT item esp" & "EFT Texture ESP" folders to the "BsgLauncher" folder? Do you need all the files within all the files to be in the "BsgLauncher" folder? or like in the "Content" folder? I'm confused.

**Comment by codsec** [comment]
@Anonymoushacker4926 There is no secret friend, just throw the files in the game folder, copy the folder's (StreamingAssets) and place it inside "EscapeFromTarkov_Data"

**Comment by Scrut1ny** [comment]
I'm so sorry about that! I sounded stupid lmfao. I didn't know that EFT put half of my files in two different drives. I couldn't find what you were talking about and was like wtf??? I found it eventually though lol, I got it all solved out and working though! Btw good shit my guy love it!
