### ISSUE TITLE
Banned.

### ISSUE THREAD

**Issue by Scrut1ny** [codsec/EFT-texture-esp#2]
Idk if it was the market bot I don't think it was... But I got banned + my friend pretty quick after I used this... RIP LOL

**Comment by duzcoo** [comment]
It is most definitely the market bot.

**Comment by Scrut1ny** [comment]
I don't think so at all cause I recoded it and everything so yeah and I've been using it for a long time never anything. But right as I start using this I get banned lol. I bet it was because too many people reported me in a short time spand. I didn't go full mf sus mode though and try and get banned lol.

**Comment by codsec** [comment]
Yeap, got detected and patched!!

**Comment by duzcoo** [comment]
@codsec any idea on how many were HWID banned or if it is a HWID ban

**Comment by Scrut1ny** [comment]
I have no clue if its just an HWID ban or IP... I'd prob say both lol
