### ISSUE TITLE
Banned as well.

### ISSUE THREAD

**Issue by duzcoo** [codsec/EFT-texture-esp#3]
Got banned at 5pm (PST) only did 1 raid didnt loot just wanted to seem, was killed by PMC. Went into offline raids to see how the item esp works and got a popup after disconnecting from the raid saying that the profile was not authorized. Not sure if HWID but it was an alt account.

**Comment by Scrut1ny** [comment]
Yeah, I think they just patched it like yesterday or today.

**Comment by codsec** [comment]
The method still works but the files have been flagged / patched

**Comment by Scrut1ny** [comment]
Damn wtf they were too fast they must've been waiting for this. And are constantly browsing UC and others lmfao
